language: cpp
jobs:
    include:
        - name: "G++ 9 test"
          os: linux
          dist: bionic
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-9
          env:
              - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

        - name: "Clang test"
          os: linux
          dist: bionic
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                      - llvm-toolchain-bionic-9.0
                  packages:
                      - clang-9.0
          env:
              - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
    - eval "${MATRIX_EVAL}"
script:
    - mkdir build
    - cd build/
    - cmake ..
    - cmake --build .
