os: linux
dist: bionic
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-9

language: cpp
compiler:
    - gcc
    - clang

script:
    - mkdir build
    - cd build/
    - cmake ..
    - cmake --build .
