matrix:
    - os: linux
      dist: bionic
      addons:
          apt:
              sources:
                  - ubuntu-toolchain-r-test
              packages:
                  - g++-9
      env:
          - MATRIX_EVAL = "CC=gcc-9 && CXX=g++-9"

language: cpp
compiler:
    - gcc
    - clang

before_install:
    - eval "${MATRIX_EVAL}"
script:
    - mkdir build
    - cd build/
    - cmake ..
    - cmake --build .
